/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_ar_core_examples_java_common_samplerender_tiny_gltf_loader */

#ifndef _Included_com_google_ar_core_examples_java_common_samplerender_tiny_gltf_loader
#define _Included_com_google_ar_core_examples_java_common_samplerender_tiny_gltf_loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_ar_core_examples_java_common_samplerender_tiny_gltf_loader
 * Method:    loadBinaryFromFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_google_ar_core_examples_java_common_samplerender_tiny_1gltf_1loader_loadBinaryFromFile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
